### PR TITLE
Defect/123 added JdbcTemplate for checking device activity. (#123)

### PR DESCRIPTION
**Pull request by YermakovSergiy**
Added JdbcTemplate for checking device activity. 
Please, make a code rewiev if you have a time: @zubrabubra , @BoldinovaNatalya , @aleksey-suprun , @vktk .

### CODE REVIEW

**Comment by vktk** [comment]
Please reduce number of commits to one.

**Comment by zubrabubra** [comment]
@vktk how does it help?

**Comment by vktk** [comment]
@zubrabubra In terms of functionality - it doesn't help.  But I don't see any reason to have four commits for change-set of four files, where some commits just removes/adds several lines of code. An idea of this pull request seems to me pretty simple and I think one commit is enought. 
Just to have clean history in open-source project. If you don't care about it - ok with me)

**Comment by zubrabubra** [comment]
@vktk huge commit could be difficult to understand, while tons of small commits are on the other hand make person to be afraid of number of changes introduced. There is no right point, while small commits make it easier to understand the logic for me, you and other reviewers :)

**Comment by vktk** [comment]
@zubrabubra Commit isn't going to be huge in this PR. It is at least splittable into two commits -  Service and Unit test. But as soon as you good - I'm good)

**Comment by zubrabubra** [comment]
Merging improvement

**Pull request merged**
