### PR TITLE
Delete unexpected fields from  websocket notification insert response

### PR DESCRIPTION
**Pull request by BoldinovaNatalya**

### CODE REVIEW

**Comment by zubrabubra** [comment]
@BoldinovaNatalya, Could you please be so kind and do same thing for CommandHandler as well?

**Comment by aleksey-suprun** [comment]
Looks good

**Comment by zubrabubra** [comment]
for me looks fine, however i against ISO8601 and passing dates as strings, forcing everyone to implement parsing infrastructure, error handling, etc.

**Comment by YermakovSergiy** [comment]
For me all looks good.

**Pull request merged**
